// <auto-generated />
using DKMart.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DKMart.Migrations
{
    [DbContext(typeof(DKSuperMarketDbContext))]
    [Migration("20220726031048_Addingmigration")]
    partial class Addingmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DkMart.Models.Category", b =>
            {
                b.Property<int>("CatId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("CatName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("DisplayOrder")
                    .HasColumnType("int");

                b.HasKey("CatId");

                b.ToTable("Category");
            });
#pragma warning restore 612, 618
        }
    }
}

