// <auto-generated />
using DKMart.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DKMart.Migrations
{
    [DbContext(typeof(DKSuperMarketDbContext))]
    [Migration("20220726043506_chnageupdate")]
    partial class chnageupdate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DKMart.Models.Category", b =>
            {
                b.Property<int>("CatId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("CatName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("DisplayOrder")
                    .HasColumnType("int");

                b.HasKey("CatId");

                b.ToTable("Category");
            });

            modelBuilder.Entity("DKMart.Models.Products", b =>
            {
                b.Property<int>("ProductId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<int>("CatId")
                    .HasColumnType("int");

                b.Property<bool>("addToWishlist")
                    .HasColumnType("bit");

                b.Property<string>("description")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("image")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<double>("price")
                    .HasColumnType("float");

                b.Property<int>("quantity")
                    .HasColumnType("int");

                b.Property<string>("title")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("ProductId");

                b.HasIndex("CatId");

                b.ToTable("Products");
            });

            modelBuilder.Entity("DKMart.Models.Products", b =>
            {
                b.HasOne("DKMart.Models.Category", "Category")
                    .WithMany()
                    .HasForeignKey("CatId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                //b.Navigation("Category");
            });
#pragma warning restore 612, 618
        }
    }
}

